/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Konstantin_Keller (https://sketchfab.com/Konstantin_Keller)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-07dd49275fc84617b5c6d3bd6a7d30a1
Title: Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = (props) => {
  const { nodes, materials } = useGLTF('/models/modern-desk.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.404, 0, -1.131]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group position={[0, 0.818, 0.413]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.metal}
          />
        </group>
        <group position={[0, 0.532, 0.44]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.black}
          />
        </group>
        <group position={[-0.266, 1.388, 0.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_0.geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={materials.paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_2.geometry}
            material={materials.folders1}
          />
        </group>
        <group position={[0.222, 1.388, 0.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_0.geometry}
            material={materials.folders2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials.paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.folders3}
          />
        </group>
        <group position={[0.675, 1.388, 0.082]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_0.geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials.paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials.folders1}
          />
        </group>
        <group position={[0.091, 1.137, 0.473]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.coffee}
          />
        </group>
        <group position={[-0.149, 1.517, 0.594]} rotation={[0, 0, 0.978]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001_0.geometry}
            material={materials.coffee}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001_1.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001_2.geometry}
            material={materials.plant_green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001_3.geometry}
            material={materials.pencil2}
          />
        </group>
        <group position={[0, 0.963, 0.454]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_0.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.pencil1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_3.geometry}
            material={materials.pencil2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_4.geometry}
            material={materials.black}
          />
        </group>
        <group position={[0.868, 1.442, 0.385]} rotation={[0, 0, 0.091]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_0.geometry}
            material={materials.folders1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials.paper}
          />
        </group>
        <group position={[0.868, 1.442, 0.42]} rotation={[0, 0, -0.314]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_0.geometry}
            material={materials.folders2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials.paper}
          />
        </group>
        <group position={[0.868, 1.442, 0.462]} rotation={[0, 0, -2.928]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_0.geometry}
            material={materials.folders3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials.paper}
          />
        </group>
        <group position={[0.868, 1.442, 0.494]} rotation={[0, 0, -0.587]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_0.geometry}
            material={materials.paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials.material}
          />
        </group>
        <group position={[0.78, -0.018, 0.225]} rotation={[0, 0, 0.445]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials.black}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_0.geometry}
          material={materials.metal}
          position={[-0.213, 0.067, 0.429]}
          rotation={[0, 0, 0.84]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_0.geometry}
          material={materials.paper}
          position={[0, 0.926, 0.429]}
          rotation={[0, 0, 0.055]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_0.geometry}
          material={materials.paper}
          position={[0, 0.958, 0.444]}
          rotation={[-0.026, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_0.geometry}
          material={materials.paper}
          position={[0, 0.938, 0.44]}
          rotation={[-0.015, 0, 0.072]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/modern-desk.glb');

export default Model;
